In [3]:
import pandas as pd

In [10]:
df = pd.read_csv('../data/Recife_Dados_imoveis.csv')

In [11]:
df

,Recife,Imóveis residenciais – Venda,Unnamed: 2,Unnamed: 3,Unnamed: 4,Imóveis residenciais-Locação,Unnamed: 6,Unnamed: 7,Unnamed: 8,Imóveis residenciais-Rentabilidade do aluguel (rental yield)
0,NaN,Número-Índice,Var. mensal (%),Var. em 12 meses (%),Preço médio (R$/m²),Número-Índice,Var. mensal (%),Var. em 12 meses (%),Preço médio (R$/m²),(% - mensalizada)
1,Data,Total,Total,Total,Total,Total,Total,Total,Total,Total
2,jan/20,"195,5","+0,00%","-1,23%",6228,"120,3","+1,03%","+7,68%","31,4","0,47%"
3,fev/20,"194,9","-0,32%","-1,43%",6208,"120,7","+0,36%","+6,65%","31,5","0,48%"
4,mar/20,"193,8","-0,55%","-1,55%",6174,"121,7","+0,84%","+7,21%","31,8","0,49%"
...,...,...,...,...,...,...,...,...,...,...
62,jan/25,"253,1","-0,18%","+5,87%",8062,"214,9","+1,12%","+15,64%","56,1","0,67%"
63,fev/25,"253,7","+0,25%","+5,05%",8082,"217,2","+1,07%","+14,86%","56,7","0,68%"
64,mar/25,"254,1","+0,16%","+3,86%",8095,"219,1","+0,87%","+14,69%","57,2","0,68%"
65,abr/25,"254,7","+0,21%","+2,81%",8112,"221,3","+1,02%","+14,05%","57,7","0,69%"
66,mai/25,"256,1","+0,55%","+2,76%",8157,NaN,NaN,NaN,NaN,NaN

In [12]:
df.describe()

,Recife,Imóveis residenciais – Venda,Unnamed: 2,Unnamed: 3,Unnamed: 4,Imóveis residenciais-Locação,Unnamed: 6,Unnamed: 7,Unnamed: 8,Imóveis residenciais-Rentabilidade do aluguel (rental yield)
count,66,67,67,67,67,66,66,66,66,66
unique,66,64,54,65,67,63,56,65,61,25
top,Data,"194,9","+0,59%","+6,36%",Preço médio (R$/m²),"122,6","+0,70%","+15,54%","31,8","0,58%"
freq,1,3,3,2,1,3,2,2,3,10

In [13]:
df.isnull().any()

Recife                                                           True
Imóveis residenciais – Venda                                    False
Unnamed: 2                                                      False
Unnamed: 3                                                      False
Unnamed: 4                                                      False
Imóveis residenciais-Locação                                     True
Unnamed: 6                                                       True
Unnamed: 7                                                       True
Unnamed: 8                                                       True
Imóveis residenciais-Rentabilidade do aluguel (rental yield)     True
dtype: bool

In [15]:
df.dtypes

Recife                                                          object
Imóveis residenciais – Venda                                    object
Unnamed: 2                                                      object
Unnamed: 3                                                      object
Unnamed: 4                                                      object
Imóveis residenciais-Locação                                    object
Unnamed: 6                                                      object
Unnamed: 7                                                      object
Unnamed: 8                                                      object
Imóveis residenciais-Rentabilidade do aluguel (rental yield)    object
dtype: object